### ISSUE TITLE
JwtFilter的73行引用JwtToken，但是在com.geekcattle.core.jwt下没有JwtToken这个类，导出报错 

### ISSUE THREAD

**Issue by DongerGroup** [liu-peiyu/Geek-Framework#13]
JwtFilter的73行引用JwtToken，但是在com.geekcattle.core.jwt下没有JwtToken这个类，导出报错

**Comment by liu-peiyu** [comment]
jwtFilter文件已经被移除，请得新拉取代码或删除jwtFilter相关导入
