### ISSUE TITLE
network.xml 报错，可以帮看下吗？

### ISSUE THREAD

**Issue by wqxcloud** [liu-peiyu/Geek-Framework#15]
network.xml 报错，可以帮看下吗？
Multiple annotations found at this line:
	- Referenced file contains errors (http://www.jgroups.org/schema/relay.xsd). For more information, right click on the message in the Problems View and 
	 select "Show Details..."
	- Referenced file contains errors (http://www.jgroups.org/schema/jgroups.xsd). For more information, right click on the message in the Problems View 
	 and select "Show Details..."

**Comment by liu-peiyu** [comment]
network.xml是j2cache的默认配置，此项目中没有用到j2cache的组群传播，真正的错误应该不是这个文件引起的
