### ISSUE TITLE
后台角色授权页面引用的treeview.js路径错误

### ISSUE THREAD

**Issue by happywan-hj** [liu-peiyu/Geek-Framework#18]
后台角色授权页面console/role/grant.html页面在第22行引用静态资源treeview.js，
但引用地址是src="/static/js/treeview.js"
在spring-boot2.x下应该去掉static，否则引用错误，造成授权页面无法出现menutree

**Comment by liu-peiyu** [comment]
谢谢指正，会尽快修复

**Comment by liu-peiyu** [comment]
已修复
