### ISSUE TITLE
为什么后台无法登录呢？

### ISSUE THREAD

**Issue by hrdzkj** [liu-peiyu/Geek-Framework#28]
端口6379是通的，数据库有数据的。 为什么后台登录不了呢？
![default](https://user-images.githubusercontent.com/12473177/51158075-b836de80-18bd-11e9-9611-dfe7a192568c.png)

**Comment by xiaobu1994** [comment]
http://localhost:8000/console/login
你登这个

**Comment by hrdzkj** [comment]
谢谢
